name: ci

on:
  push:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  npm-ci-and-pulumi-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm ci

      - name: Run tests ğŸ§ª
        run: npm run test

      - name: Generate Static Site from Nuxt.js application
        run: npm run generate

      - name: After setting up the Pulumi project specific language environment, we need to install the dependencies also (see https://github.com/pulumi/actions#example-workflows)
        run: npm install
        working-directory: ./deployment

      - name: Install Pulumi CLI so that we can create a GHA pipeline specific Pulumi Stack
        uses: pulumi/action-install-pulumi-cli@v1.0.2

      - name: Create GHA pipeline specific Pulumi Stack & set Pulumi aws:region
        run: |
          pulumi stack init github-${{ github.run_id }}
          pulumi config set aws:region eu-central-1
        working-directory: ./deployment

      - name: Run pulumi preview and pulumi up
        run: |
          pulumi preview --stack github-${{ github.run_id }}
          pulumi up --stack github-${{ github.run_id }} -y
        working-directory: ./deployment

      - name: Configure AWS credentials for GitHub pre-installed AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Nuxt.js generated static site to S3 Bucket via AWS CLI
        run: aws s3 sync ../dist/ s3://$(pulumi stack output bucketName) --acl public-read
        working-directory: ./deployment
