name: ci

on:
  push:
  pull_request:

jobs:
  npm-ci-and-pulumi-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm ci

      - name: Run tests ğŸ§ª
        run: npm run test

      - name: After setting up the Pulumi project specific language environment, we need to install the dependencies also (see https://github.com/pulumi/actions#example-workflows)
        run: npm install
        working-directory: ./deployment

      - name: Install Pulumi CLI so that we can create a GHA pipeline specific Pulumi Stack
        uses: pulumi/action-install-pulumi-cli@v1.0.2

      - name: Create GHA pipeline specific Pulumi Stack
        run: |
          cd deployment
          pulumi stack init github-${{ github.run_id }}

      - name: Preview pulumi up
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: github-${{ github.run_id }}
          work-dir: deployment

      - name: Actually run pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: github-${{ github.run_id }}
          work-dir: deployment

      - name: Deploy Nuxt.js generated static site to S3 Bucket via AWS CLI
        run: aws s3 sync ../dist/ s3://$(pulumi stack output bucketName) --acl public-read
        working-directory: ./deployment
